language: node_js
node_js:
  - '0.8'
  - '0.10'
  - '4'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
sudo: false
cache: yarn
before_install:
  - npm install --global nyc codecov coveralls
script:
  - npm run build
  - nyc npm run test
after_script:
  - nyc report --reporter=text-lcov | coveralls
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
